version: '3.4'
services:
 eshopwebmvc:
   iamge: 767398037269.dkr.ecr.us-east-1.amazonaws.com/cloudshirtrepo:web
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5106:80"
   volumes:
     - ~/.aspnet/https:/root/.aspnet/https:ro
     - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
     
 eshoppublicapi:
   iamge: 767398037269.dkr.ecr.us-east-1.amazonaws.com/cloudshirtrepo:publicapi
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5200:80"
   volumes:
     - ~/.aspnet/https:/root/.aspnet/https:ro
     - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
